name: CI

IDEAS

Search or jump to...

on: [push, workflow_dispatch]

Pull requests Issues Marketplace

jobs: build:

deshikajayantha / rdptest1

Public

runs on: windows-latest

<> Code

Issues

Pull requests

Actions

Projects

Wiki

rdptest1/.github/workflows/main.yml

in main

steps:

- name:

Download

run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok stable-windows-amd64.zip -OutFile ngrok.zip

- name: Extract

run: Expand-Archive ngrok.zip

- name:

Auth

run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

<> Edit new file

Preview

Spaces

env:

NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

- name: Enable TS

run: Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control \Terminal Server name "fDenyTSConnections" -Value @

- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

run: Set-ItemProperty -Path "HKLM: \System\CurrentControlSet\Control \Terminal Server\WinStations RDP-Tcp -name "UserAuthentication" -Value 1 - run: Set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssword!" -Force)

name: Create Tunnel

run: .\ngrok\ngrok.exe tcp 3389
